# Generated by Django 4.2.1 on 2026-09-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(choices=[(0, 'Нет в наличии'), (1, 'В наличии')], default=1, verbose_name='Наличие')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='drinks_drin_time_cr_c961d4_idx')],
            },
        ),
    ]
