# Generated by Django 4.2.1 on 2026-09-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_drink_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['-time_create'], 'permissions': [('can_publish_drink', 'Может публиковать напитки')], 'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
    ]
