# Generated by Django 4.2.1 on 2026-09-19 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinks', '0004_alter_drink_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drinks', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='drink',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_drinks', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='drink',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_drinks', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='drink',
            name='reposted_by',
            field=models.ManyToManyField(blank=True, related_name='reposted_drinks', to=settings.AUTH_USER_MODEL, verbose_name='Репосты'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='drinks.drink', verbose_name='Напиток')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-time_create'],
            },
        ),
    ]
